"""report model added

Revision ID: b9cf385b41d1
Revises: b8e51de9a946
Create Date: 2025-12-14 23:15:14.785261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9cf385b41d1'
down_revision: Union[str, Sequence[str], None] = 'b8e51de9a946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_count', sa.BigInteger(), nullable=False),
    sa.Column('group_time', sa.String(), nullable=True),
    sa.Column('group_month', sa.String(), nullable=True),
    sa.Column('group_lesson', sa.String(), nullable=True),
    sa.Column('student_count', sa.BigInteger(), nullable=False),
    sa.Column('student_paid', sa.BigInteger(), nullable=False),
    sa.Column('exam_day', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
