"""report model added

Revision ID: ef0f4f726341
Revises: 633da026662d
Create Date: 2025-12-14 23:32:08.253524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0f4f726341'
down_revision: Union[str, Sequence[str], None] = '633da026662d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('weekly_report_id', sa.BigInteger(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('group_time', sa.String(), nullable=False),
    sa.Column('student_count', sa.BigInteger(), nullable=False),
    sa.Column('student_present', sa.BigInteger(), nullable=False),
    sa.Column('student_paid', sa.BigInteger(), nullable=False),
    sa.Column('exam_day', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['weekly_report_id'], ['weekly_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('group_count', sa.BIGINT(), nullable=False),
    sa.Column('group_time', sa.VARCHAR(), nullable=True),
    sa.Column('group_month', sa.VARCHAR(), nullable=True),
    sa.Column('group_lesson', sa.VARCHAR(), nullable=True),
    sa.Column('student_count', sa.BIGINT(), nullable=False),
    sa.Column('student_paid', sa.BIGINT(), nullable=False),
    sa.Column('exam_day', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('student_present', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.drop_table('group_reports')
    op.drop_table('weekly_reports')
    # ### end Alembic commands ###
